version: 2
jobs:
  build:
    docker:
      - image: tmaier/docker-compose
        environment:
          COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: setup
          command: |
            set -x
            docker info
            docker volume create project
            docker create -v project:/app --name project busybox chown -R 1000:1000 /app
            docker cp . project:/app
            docker start project
            docker-compose build
      - run:
          name: test
          command: |
            docker-compose run app bundle exec rake test
            docker-compose run ruby-2-4 bundle exec rake test
            docker-compose run ruby-2-3 bundle exec rake test
            docker-compose run ruby-2-2 bundle exec rake test
